id: privatecctv
name: Private CCTV
version: 1.1.0
author: yudhisthereal
icon: ''
desc: >-
  a privacy preserving cctv where human figures are replaced by stickman
  figures, complete with fall detection and recording (video and csv for
  keypoints) features.
files:
  - model/yolo11n_pose.mud
  - model/yolo11n-pose_320x224_int8.cvimodel
  - pose/__init__.py
  - pose/judge_fall.py
  - pose/pose_estimation.py
  - tools/__init__.py
  - tools/bed_area_checker.py
  - tools/bench_area_checker.py
  - tools/chair_area_checker.py
  - tools/couch_area_checker.py
  - tools/floor_area_checker.py
  - tools/log_manager.py
  - tools/polygon_checker.py
  - tools/safety_judgment.py
  - tools/skeleton_saver.py
  - tools/time_utils.py
  - tools/video_record.py
  - tools/web_server.py
  - tools/wifi_connect.py
  - camera_manager.py
  - config.py
  - control_manager.py
  - debug_config.py
  - main.py
  - streaming.py
  - tracking.py
  - workers.py
